### ISSUE TITLE
Getting cannot import config

### ISSUE THREAD

**Issue by zubinmehta** [emaillenin/open-cricket#2]
I am just trying this out and I got the following error:

-> % python3 flaskr.py
Traceback (most recent call last):
  File "flaskr.py", line 8, in <module>
    from opencricket.config import config
ImportError: cannot import name 'config'

I see there is nothing named config inside the config folder.

**Comment by uttusharma** [comment]
After this commit [3d4d89d](https://github.com/emaillenin/open-cricket/commit/3d4d89d4ac162afea686a5f2d81a4cad61030716#diff-c2d9a61eb772eb0ca417966554e36654) config.py is added in the project. git.ignore contains a config.py entry 
**Solution/Work Around**
renaming **config.ci.py** to **config.py** will do the job 
located at : _\opencricket\config.ci.py_

**Comment by uttusharma** [comment]
> I am just trying this out and I got the following error:
> 
> -> % python3 flaskr.py
> Traceback (most recent call last):
> File "flaskr.py", line 8, in
> from opencricket.config import config
> ImportError: cannot import name 'config'
> 
> I see there is nothing named config inside the config folder.

After this commit 3d4d89d config.py is added in the project. git.ignore contains a config.py entry

---Solution/Work Around---

renaming config.ci.py to config.py will do the job
located at : \opencricket\config.ci.py

**Comment by uttufy** [comment]
After this commit 3d4d89d config.py is added in the project. git.ignore contains a config.py entry

**---Solution/Work Around---**

renaming **_config.ci.py_** to **_config.py_** will do the job
located at : _\opencricket\config.ci.py_
